[
  ./cpufreq.nix
  ./eudev.nix
  ./grub/grub.nix
  ./grub/ipxe.nix
  ./haveged.nix
  ./htop.nix
  ./logrotate.nix
  ./lxcfs.nix
  ./nfs.nix
  ./nix-daemon.nix
  ./node_exporter.nix
  ./osctl/pools.nix
  ./osctld.nix
  ./programs/bash.nix
  ./rename.nix
  ./rpcbind.nix
  ./rsyslog.nix
  ./runit
  ./services/mail/opensmtpd.nix
  ./services/networking/bird.nix
  ./services/networking/chronyd.nix
  ./services/networking/dhcpd.nix
  ./services/osctl/image-repository.nix
  ./services/scheduling/cron.nix
  ./sshd.nix
  ./system/boot/qemu.nix
  ./tasks/network-interfaces.nix
  ./tools/tools.nix
  ./tty.nix
  ./version.nix
  ./vpsadmin.nix
  ./zfs
]
