[
  ./bash.nix
  ./bird.nix
  ./chronyd.nix
  ./crond.nix
  ./cpufreq.nix
  ./dhcpd.nix
  ./eudev.nix
  ./grub/grub.nix
  ./grub/ipxe.nix
  ./haveged.nix
  ./htop.nix
  ./logrotate.nix
  ./lxcfs.nix
  ./networking.nix
  ./nfs.nix
  ./nix-daemon.nix
  ./node_exporter.nix
  ./osctl/pools.nix
  ./osctld.nix
  ./rename.nix
  ./rpcbind.nix
  ./rsyslog.nix
  ./runit
  ./services/mail/opensmtpd.nix
  ./services/osctl/image-repository.nix
  ./sshd.nix
  ./tools/tools.nix
  ./tty.nix
  ./version.nix
  ./vpsadmin.nix
  ./zfs
]
