[
  ./config/defaults.nix
  ./config/kernel.nix
  ./config/runit.nix
  ./config/system-path.nix
  ./config/tunables.nix
  ./misc/manual.nix
  ./misc/os-lib.nix
  ./misc/version.nix
  ./nixos-compat.nix
  ./osctl/pools.nix
  ./osctl/osctld.nix
  ./osctl/osctl-exporter.nix
  ./osctl/osctl-exportfs.nix
  ./programs/bash.nix
  ./programs/htop.nix
  ./rename.nix
  ./services/hardware/eudev.nix
  ./services/logging/logrotate.nix
  ./services/logging/rsyslog.nix
  ./services/mail/opensmtpd.nix
  ./services/misc/nix-daemon.nix
  ./services/monitoring/munin.nix
  ./services/monitoring/prometheus/node_exporter.nix
  ./services/network-filesystems/nfs.nix
  ./services/networking/bird.nix
  ./services/networking/chronyd.nix
  ./services/networking/dhcpd.nix
  ./services/networking/firewall.nix
  ./services/networking/rpcbind.nix
  ./services/networking/sshd.nix
  ./services/osctl/image-repository
  ./services/scheduling/cron.nix
  ./services/security/haveged.nix
  ./services/ttys/agetty.nix
  ./system/activation/top-level.nix
  ./system/activation/secrets.nix
  ./system/boot/loader/grub/grub.nix
  ./system/boot/loader/grub/ipxe.nix
  ./system/boot/qemu.nix
  ./system/boot/restrict-proc-sysfs
  ./system/boot/runit
  ./system/boot/stage-1.nix
  ./system/boot/stage-2.nix
  ./tasks/cpu-freq.nix
  ./tasks/filesystems/zfs
  ./tasks/network-interfaces.nix
  ./tools/tools.nix
  ./virtualisation/lxcfs.nix
  ./vpsadmin/nodectld.nix
]
