inherit_from:
  - ../../.rubocop.yml

RSpec/AnyInstance:
  Enabled: false

RSpec/EmptyLineAfterFinalLet:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Style/OpenStructUse:
  Enabled: false
