lxc.include = /etc/lxc/config/common.conf
lxc.include = /etc/lxc/config/userns.conf

lxc.mount.entry = /run/osctl/debugfs sys/kernel/debug none rbind,ro,optional,create=dir 0 0
lxc.mount.entry = /run/osctl/tracing sys/kernel/tracing none rbind,ro,optional,create=dir 0 0
lxc.mount.entry = /run/osctl/securityfs sys/kernel/security none bind,optional,create=dir 0 0
lxc.mount.entry = /sys/fs/pstore sys/fs/pstore none bind,optional 0 0
lxc.mount.entry = mqueue dev/mqueue mqueue rw,relatime,create=dir,optional 0 0
