inherit_from: .rubocop_todo.yml
require: rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - '*.rb'
    - 'libosctl/*.rb'
    - 'osctl/*.rb'
    - 'osctld/*.rb'
    <% `git status --ignored --porcelain`.lines.grep(/^!! /).each do |path| %>
    - <%= path.sub(/^!! /, '').sub(/\/$/, '/**/*') %>
    <% end %>

Bundler/DuplicatedGem:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Lint/NestedMethodDefinition:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/FileName:
  Exclude:
    - converter/lib/vpsadminos-converter.rb
    - test-runner/lib/test-runner.rb
Naming/MethodParameterName:
  Enabled: false
Naming/PredicateName:
  Enabled: false

Style/CaseEquality:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/CombinableLoops:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
  EnforcedStyle: template
Style/FrozenStringLiteralComment:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/NumericPredicate:
  Enabled: true
  EnforcedStyle: comparison
Style/PreferredHashMethods:
  Enabled: true
  EnforcedStyle: verbose
Style/RedundantConstantBase:
  Enabled: false
Style/RedundantLineContinuation:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: true
  RequireEnglish: false
  EnforcedStyle: use_perl_names
