source 'https://rubygems.org'
gemspec

gem 'libosctl', path: '../libosctl'
gem 'osctl', path: '../osctl'
gem 'osctl-repo', path: '../osctl-repo'

group :development do
  gem 'md2man'
  gem 'rake'
  gem 'rspec', '~> 3.13'
  gem 'yard'
end
