inherit_from:
  - ../../.rubocop.yml

RSpec/AnyInstance:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false
