#!/usr/bin/env ruby
require 'json'
require 'socket'

ctid = ENV.fetch('LXC_NAME', nil)
run_id = ENV.fetch('OSCTL_RUN_ID', nil)

if ctid.nil? || run_id.nil?
  warn 'Expected environment variables:'
  warn '  LXC_NAME'
  warn '  OSCTL_RUN_ID'
  exit(false)
end

if %r{^/run/osctl/pools/([^/]+)/hooks} !~ $0
  warn "Unable to detect pool name from '#{$0}'"
  exit(false)
end

pool = Regexp.last_match(1)

opts = {
  id: ctid,
  pool:,
  run_id:
}

s = UNIXSocket.new("/run/osctl/user-control/#{Process.uid}.sock")
s.puts({ cmd: :ct_on_start, opts: }.to_json)
ret = JSON.parse(s.readline, symbolize_names: true)
s.close

exit if ret[:status]
warn "Error: #{ret[:message]}"
exit(false)
