#!/usr/bin/env ruby
require 'json'
require 'socket'

ctid = ENV.fetch('LXC_NAME', nil)

if ctid.nil?
  warn 'Expected environment variables:'
  warn '  LXC_NAME'
  exit(false)
end

if %r{^/run/osctl/pools/([^/]+)/hooks} !~ $0
  warn "Unable to detect pool name from '#{$0}'"
  exit(false)
end

pool = Regexp.last_match(1)

s = UNIXSocket.new("/run/osctl/user-control/#{Process.uid}.sock")
s.puts({ cmd: :ct_on_start, opts: {
  id: ctid,
  pool:
} }.to_json)
ret = JSON.parse(s.readline, symbolize_names: true)
s.close

exit(true) if ret[:status]
warn "Error: #{ret[:message]}"
exit(false)
