#!/usr/bin/env ruby
require 'fiddle'
require 'fiddle/import'
require 'json'
require 'socket'

module Sys
  MS_MGC_VAL = 0xc0ed0000
  MS_BIND = 4096

  module Int
    extend Fiddle::Importer
    dlload Fiddle.dlopen(nil)

    extern 'int mount(const char *source, const char *target,           ' \
           'const char *filesystemtype, unsigned long mountflags,           ' \
           'const void *data)'
  end

  def self.bind_mount(src, dst)
    ret = Int.mount(src, dst, 0, MS_MGC_VAL | MS_BIND, 0)
    raise SystemCallError, Fiddle.last_error if ret != 0

    ret
  end
end

class CtPostMount
  ROOTFS_DESCRIPTOR_REQUEST = 'send-rootfs-mount-fd'.freeze

  def initialize(pool, ctid, run_id, rootfs_dir)
    @pool = pool
    @ctid = ctid
    @run_id = run_id
    @rootfs_dir = rootfs_dir
  end

  def run
    call_osctld!
  end

  protected

  def call_osctld!
    s = UNIXSocket.new('/run/osctl/user-control/namespaced.sock')
    begin
      s.puts({ cmd: :ct_post_mount, opts: {
        id: @ctid,
        pool: @pool,
        run_id: @run_id
      } }.to_json)

      request = JSON.parse(s.readline, symbolize_names: true)
      unless request[:status] && request[:progress] == ROOTFS_DESCRIPTOR_REQUEST
        warn "Error: #{request[:message] || 'server did not request the mounted rootfs descriptor'}"
        exit(false)
      end

      s.send_io(@rootfs_dir)
      ret = JSON.parse(s.readline, symbolize_names: true)
    ensure
      s.close unless s.closed?
    end

    unless ret[:status]
      warn "Error: #{ret[:message]}"
      exit(false)
    end

    ret
  end
end

ctid = ENV.fetch('LXC_NAME', nil)
run_id = ENV.fetch('OSCTL_RUN_ID', nil)
rootfs_fd = ENV.fetch('LXC_ROOTFS_MOUNT_FD', nil)

if ctid.nil? || run_id.nil? || rootfs_fd.nil?
  warn 'Expected environment variables:'
  warn '  LXC_NAME'
  warn '  OSCTL_RUN_ID'
  warn '  LXC_ROOTFS_MOUNT_FD'
  exit(false)
end

begin
  rootfs_dir = IO.for_fd(Integer(rootfs_fd, 10), autoclose: false)
  raise Errno::ENOTDIR unless rootfs_dir.stat.directory?
rescue SystemCallError, IOError, ArgumentError, TypeError => e
  warn "Invalid mounted rootfs descriptor: #{e.message}"
  exit(false)
end

if %r{^/run/osctl/pools/([^/]+)/hooks} !~ $0
  warn "Unable to detect pool name from '#{$0}'"
  exit(false)
end

pool = Regexp.last_match(1)

hook = CtPostMount.new(pool, ctid, run_id, rootfs_dir)
hook.run

exit
