#!/usr/bin/env ruby
require 'json'
require 'socket'

ctid = ARGV[0]
veth = ARGV[4]

if ctid.nil? || veth.nil?
  warn "Expected arguments: <ctid> net up veth <devname>, "+
       "received #{ARGV.join(' ')}"
  exit(false)
end

s = UNIXSocket.new("/run/osctl/user-control/#{Process.uid}.sock")
s.send({cmd: :veth_up, opts: {
  id: ARGV[0],
  veth: ARGV[4],
}}.to_json + "\n", 0)
ret = JSON.parse(s.readline, symbolize_names: true)
s.close

exit(true) if ret[:status]
warn "Error: #{ret[:message]}"
exit(false)
