#!/usr/bin/env ruby
require 'json'
require 'socket'

ctid = ENV['LXC_NAME']
veth = ENV['LXC_NET_PEER']

if ctid.nil? || veth.nil?
  warn 'Expected environment variables:'
  warn '  LXC_NAME'
  warn '  LXC_NET_PEER'
  exit(false)
end

if /^\/run\/osctl\/pools\/([^\/]+)\/hooks/ !~ $0
  warn "Unable to detect pool name from '#{$0}'"
  exit(false)
end

pool = $1

base = File.basename($0)
ctid2, ifname = base.split('.')

if ctid != ctid2
  warn "Expected to handle CT '#{ctid2}', but was called for '#{ctid}' instead"
  exit(false)

elsif !ifname
  warn "Expected to be called via symlink named as: <ctid>.<interface>, "+
    "called as '#{base}' instead"
  exit(false)
end

s = UNIXSocket.new("/run/osctl/user-control/#{Process.uid}.sock")
s.send({cmd: :veth_down, opts: {
  id: ctid,
  pool: pool,
  interface: ifname,
  veth: veth,
}}.to_json + "\n", 0)
ret = JSON.parse(s.readline, symbolize_names: true)
s.close

exit(true) if ret[:status]
warn "Error: #{ret[:message]}"
exit(false)
