source 'https://rubygems.org'
gemspec

gem 'libosctl', path: '../libosctl'
gem 'netlinkrb', path: ENV.fetch('NETLINKRB_PATH')
gem 'osctl-repo', path: '../osctl-repo'
gem 'osup', path: '../osup'
gem 'ruby-lxc', path: ENV.fetch('RUBY_LXC_PATH')

group :development do
  gem 'memory_profiler'
  gem 'rake'
  gem 'rake-compiler'
  gem 'yard'
end

group :test do
  gem 'rspec', '~> 3.13'
end
