source 'https://rubygems.vpsfree.cz'
gemspec


unless ENV.has_key?('OS_BUILD_ID')
  gem 'libosctl', path: '../libosctl'
  gem 'osctl-repo', path: '../osctl-repo'
  gem 'osup', path: '../osup'
  gem 'memory_profiler'
end
