source 'https://rubygems.org'
gemspec

source 'https://rubygems.vpsfree.cz' do
  gem 'netlinkrb'
  gem 'ruby-lxc'
end

if ENV.has_key?('OS_BUILD_ID')
  source 'https://rubygems.vpsfree.cz' do
    gem 'libosctl'
    gem 'osctl-repo'
    gem 'osup'
  end
else
  gem 'libosctl', path: '../libosctl'
  gem 'memory_profiler'
  gem 'osctl-repo', path: '../osctl-repo'
  gem 'osup', path: '../osup'
end
