require 'bundler/gem_tasks'

begin
  require 'yard'

  YARD::Rake::YardocTask.new do |t|
    t.files   = ['lib/**/*.rb']
    t.options = [
      '--protected',
      '--output-dir=html_doc',
    ]
  end

rescue LoadError
end
