require 'bundler/gem_tasks'
require 'rake/extensiontask'
require 'yard'
require_relative './yard/lockable'

gemspec = Gem::Specification.load('osctld.gemspec')

Rake::ExtensionTask.new do |ext|
  ext.name = 'native'
  ext.source_pattern = "*.{c,h}"
  ext.ext_dir = 'ext/osctld'
  ext.lib_dir = 'lib/osctld'
  ext.gem_spec = gemspec
end

YARD::Rake::YardocTask.new do |t|
  t.files   = ['ext/**/*.c', 'lib/**/*.rb']
  t.options = [
    '--protected',
    "--output-dir=#{ENV['YARD_OUTPUT'] || 'html_doc'}",
  ]
end
