source 'https://rubygems.org'
gemspec

gem 'libosctl', path: '../libosctl'
gem 'osctl', path: '../osctl'
gem 'osctl-exportfs', path: '../osctl-exportfs'

group :development do
  gem 'rackup'
  gem 'rake'
  gem 'yard'
end

group :test do
  gem 'rspec', '~> 3.13'
end
