require 'bundler/gem_tasks'
require 'yard'

YARD::Rake::YardocTask.new do |t|
  t.files   = ['lib/**/*.rb']
  t.options = [
    '--protected',
    "--output-dir=#{ENV['YARD_OUTPUT'] || 'html_doc'}"
  ]
end
