source 'https://rubygems.org'
gemspec

if ENV.has_key?('OS_BUILD_ID')
  source 'https://rubygems.vpsfree.cz' do
    gem 'libosctl'
    gem 'osvm'
  end
else
  gem 'libosctl', path: '../libosctl'
  gem 'osvm', path: '../osvm'
end

group :development do
  gem 'md2man'
  gem 'rake'
  gem 'yard'
end
