source 'https://rubygems.org'
gemspec

if ENV.has_key?('OS_BUILD_ID')
  gem 'libosctl', source: 'https://rubygems.vpsfree.cz'
else
  gem 'libosctl', path: '../libosctl'
end

group :development do
  gem 'md2man'
  gem 'rake'
  gem 'rspec', '~> 3.13'
  gem 'yard'
end
