name: Build all kernel versions

on:
  schedule:
    - cron: '5 3 * * *'
  push:
    branches:
     - staging
    paths:
      - .github/workflows/kernels.yml
      - os/packages/linux/**
      - os/configs/nfs-cancellation-debug.nix
  pull_request:
    branches:
     - staging
    paths:
      - .github/workflows/kernels.yml
      - os/packages/linux/**
      - os/configs/nfs-cancellation-debug.nix

jobs:
  detect:
    name: Detect available kernel versions
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v31.11.1

      - id: set
        shell: bash
        run: |
          matrix=$(nix eval --json .#lib.kernelBuildMatrix)
          echo "Detected kernel builds: $matrix"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  build:
    name: Kernel ${{ matrix.kernel }} (diagnostic=${{ matrix.diagnostic }})
    needs: detect
    runs-on: self-hosted
    strategy:
      matrix: ${{ fromJson(needs.detect.outputs.matrix) }}
    timeout-minutes: 480

    steps:
      - uses: actions/checkout@v7.0.1

      - name: Determine branch name
        id: vars
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Build toplevel closure with kernel ${{ matrix.kernel }}
        run: |
          KERNEL_OUTPUT_VERSION="${{ matrix.kernel }}"
          KERNEL_OUTPUT_VERSION="${KERNEL_OUTPUT_VERSION//[.-]/_}"
          if [[ '${{ matrix.diagnostic }}' == true ]]; then
            KERNEL_OUTPUT="ci-nfs-debug-kernel-$KERNEL_OUTPUT_VERSION"
          else
            KERNEL_OUTPUT="ci-toplevel-kernel-$KERNEL_OUTPUT_VERSION"
          fi
          make OUTPUT="$KERNEL_OUTPUT" toplevel
          echo "BUILD_OUT=$(readlink -f os/result/toplevel)" >> $GITHUB_ENV

      - name: Copy toplevel closure with kernel ${{ matrix.kernel }} to binary cache
        env:
          VPSADMINOS_CACHE_SSH_KEY: ${{ secrets.VPSADMINOS_CACHE_SSH_KEY }}
        run: |
          install -m 600 -D <(echo "$VPSADMINOS_CACHE_SSH_KEY") .ssh/cache_id
          NIX_SSHOPTS="-i .ssh/cache_id -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" nix-copy-closure --to push@cache.int.vpsadminos.org "$BUILD_OUT"

      - name: Add new profile generation for kernel ${{ matrix.kernel }}
        env:
          BRANCH: ${{ steps.vars.outputs.branch }}-kernel-${{ matrix.kernel }}${{ matrix.diagnostic && '-debug' || '' }}
        run: |
          ssh -i .ssh/cache_id \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              push@cache.int.vpsadminos.org \
              sudo push-ci-generation "$BRANCH" "$BUILD_OUT"
